name: ERP_RANGER
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #SpinKit
  geolocator: ^6.0.0
  flutter_spinkit: ^4.1.2
  progress_indicators: ^0.1.5
  social_share: ^2.0.5
  network_to_file_image: ^2.3.2
  image_downloader: ^0.20.0
  maps_launcher: ^1.2.2+1
  camera: 
  path:
  flutter_typeahead: ^1.8.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.9+2

  # state management
  stacked: ^1.7.1+1
  observable_ish:
  stacked_hooks: ^0.1.2
  flutter_hooks: ^0.9.0
  shared_preferences: ^0.5.8
  
  # navigation
  auto_route: ^0.6.1
  stacked_services: ^0.5.4+2

  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  provider: ^4.3.0
  http: ^0.12.2

  # grahpql
  graphql_flutter: ^3.0.0

  # image picker
  image_picker: ^0.6.3+4

  # bages 
  badges: ^1.1.1

  # download
  dio: any
  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner:
  flutter_launcher_icons:
  auto_route_generator: ^0.6.0
  injectable_generator:
  google_maps_flutter:
  carousel_slider: ^2.2.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MavenPro
      fonts:
        - asset: fonts/MavenPro-Black.ttf
        - asset: fonts/MavenPro-Bold.ttf
        - asset: fonts/MavenPro-ExtraBold.ttf
        - asset: fonts/MavenPro-Medium.ttf
        - asset: fonts/MavenPro-Regular.ttf
        - asset: fonts/MavenPro-SemiBold.ttf
    - family: MyCustomIcons
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/logo.jpeg
    - assets/images/image.jpg
    - assets/images/image.png
    - assets/images/images.png
    - assets/images/buffalo.jpeg
    - assets/images/Elephant.jpeg
    - assets/images/Red_Hartebeest.jpg
    - assets/images/rhino.jpeg
    - assets/images/springbok.jpg
    - assets/images/Blesbok.jpg
    - assets/images/profile.png
    - assets/images/serverError.jpg
    - assets/images/internet.png
    - assets/images/E1.jpg
    - assets/images/ANV5.jpeg
    - assets/images/trophy.png
    - assets/images/trophy2.png
    - assets/images/circle.png
    - assets/images/ERP_Tech.png

    - assets/images/print/buffalo/print1.jpg
    - assets/images/print/buffalo/print2.jpg
    - assets/images/print/buffalo/print3.jpg
    - assets/images/print/buffalo/print4.jpg

    - assets/images/print/elephant/print1.jpg
    - assets/images/print/elephant/print2.jpg
    - assets/images/print/elephant/print3.jpg
    - assets/images/print/elephant/print4.jpg

    - assets/images/print/rhino/print1.jpg
    - assets/images/print/rhino/print2.jpg
    - assets/images/print/rhino/print3.jpg
    - assets/images/print/rhino/print4.jpg
    - assets/images/print/rhino/print5.jpg

    - assets/images/print/lion/print1.jpg
    - assets/images/print/lion/print2.jpg
    - assets/images/print/lion/print3.jpg
    - assets/images/print/lion/print4.jpg

    - assets/images/print/springbok/print1.jpg

    - assets/images/print/blesbok/print1.jpg

    - assets/images/print/cheetah/print1.jpg
    - assets/images/print/cheetah/print2.jpg
    - assets/images/print/cheetah/print3.jpg


    - assets/images/print/leopard/print1.jpg
    - assets/images/print/leopard/print2.jpg
    - assets/images/print/leopard/print3.jpg

    - assets/images/appearance/buffalo/p1.jpg
    - assets/images/appearance/buffalo/p2.jpg
    - assets/images/appearance/buffalo/p3.jpg
    - assets/images/appearance/buffalo/p4.jpg

    - assets/images/appearance/blesbok/p1.jpg
    - assets/images/appearance/blesbok/p2.jpg
    - assets/images/appearance/blesbok/p3.jpg
    - assets/images/appearance/blesbok/p4.jpg
    
    - assets/images/appearance/elephant/p1.jpg
    - assets/images/appearance/elephant/p2.jpg
    - assets/images/appearance/elephant/p3.jpg
    - assets/images/appearance/elephant/p4.jpg

    - assets/images/appearance/rhino/p1.jpg
    - assets/images/appearance/rhino/p2.jpg
    - assets/images/appearance/rhino/p3.jpg
    - assets/images/appearance/rhino/p4.jpg

    - assets/images/appearance/springbok/p1.jpg
    - assets/images/appearance/springbok/p2.jpg
    - assets/images/appearance/springbok/p3.jpg
    - assets/images/appearance/springbok/p4.jpg
    
    - assets/images/appearance/hartebeest/p1.jpg
    - assets/images/appearance/hartebeest/p2.jpg
    - assets/images/appearance/hartebeest/p3.jpg
    - assets/images/appearance/hartebeest/p4.jpg

    - assets/images/appearance/leopard/p1.jpg
    - assets/images/appearance/leopard/p2.jpg
    - assets/images/appearance/leopard/p3.jpg
    - assets/images/appearance/leopard/p4.jpg

    - assets/images/appearance/cheetah/p1.jpg
    - assets/images/appearance/cheetah/p2.jpg
    - assets/images/appearance/cheetah/p3.jpg
    - assets/images/appearance/cheetah/p4.jpg

    - assets/images/droppings/buffalo/drop1.jpg
    - assets/images/droppings/buffalo/drop2.jpg
    - assets/images/droppings/buffalo/drop3.jpg
    - assets/images/droppings/buffalo/drop4.jpg
    
    - assets/images/droppings/elephant/drop1.jpg
    - assets/images/droppings/elephant/drop2.jpg
    - assets/images/droppings/elephant/drop3.jpg
    - assets/images/droppings/elephant/drop4.jpg

    - assets/images/droppings/lion/drop1.jpg
    - assets/images/droppings/lion/drop2.jpg
    - assets/images/droppings/lion/drop3.jpg

    - assets/images/droppings/rhino/drop1.jpg
    - assets/images/droppings/rhino/drop2.jpg
    - assets/images/droppings/rhino/drop3.jpg

    - assets/images/droppings/springbok/drop1.jpg
    - assets/images/droppings/springbok/drop2.jpg
    - assets/images/droppings/springbok/drop3.jpg
    
    - assets/images/droppings/blesbok/drop1.jpg
    - assets/images/droppings/blesbok/drop2.jpg

    - assets/images/droppings/leopard/drop1.jpg
    - assets/images/droppings/leopard/drop2.jpg
    - assets/images/droppings/leopard/drop3.jpg

    - assets/images/droppings/cheetah/drop1.jpg


    - assets/images/animal/Big_Cats/cheetah/a1.jpg
    - assets/images/animal/Big_Cats/cheetah/a2.jpg
    - assets/images/animal/Big_Cats/cheetah/a3.jpg
    - assets/images/animal/Big_Cats/cheetah/a4.jpg

    - assets/images/animal/Big_Cats/leopard/a1.jpg
    - assets/images/animal/Big_Cats/leopard/a2.jpg
    - assets/images/animal/Big_Cats/leopard/a3.jpg
    - assets/images/animal/Big_Cats/leopard/a4.jpg

    - assets/images/animal/Big_Cats/lion/a1.jpeg
    - assets/images/animal/Big_Cats/lion/a2.jpg
    - assets/images/animal/Big_Cats/lion/a3.jpg
    - assets/images/animal/Big_Cats/lion/a4.jpg

    - assets/images/animal/Big_Five/buffalo/p1.jpg
    - assets/images/animal/Big_Five/buffalo/p2.jpg
    - assets/images/animal/Big_Five/buffalo/p3.jpg
    - assets/images/animal/Big_Five/buffalo/p4.jpg

    - assets/images/animal/Big_Five/elephant/p1.jpg
    - assets/images/animal/Big_Five/elephant/p2.jpg
    - assets/images/animal/Big_Five/elephant/p3.jpg
    - assets/images/animal/Big_Five/elephant/p4.jpg

    - assets/images/animal/Big_Five/lion/a1.jpeg
    - assets/images/animal/Big_Five/lion/a2.jpg
    - assets/images/animal/Big_Five/lion/a3.jpg
    - assets/images/animal/Big_Five/lion/a4.jpg

    - assets/images/animal/Antelopes/eland/a1.jpg
    - assets/images/animal/Antelopes/eland/a2.jpg
    - assets/images/animal/Antelopes/eland/a3.jpg

    - assets/images/animal/Antelopes/hartebeest/a1.jpg
    - assets/images/animal/Antelopes/hartebeest/a2.jpg
    - assets/images/animal/Antelopes/hartebeest/a3.jpg

    - assets/images/animal/Antelopes/kudu/a1.jpg
    - assets/images/animal/Antelopes/kudu/a2.jpg
    - assets/images/animal/Antelopes/kudu/a3.jpg

    - assets/images/trophies/bronze.png
    - assets/images/trophies/gold.png
    - assets/images/trophies/hunter.png
    - assets/images/trophies/military.png
    - assets/images/trophies/silver.png
    - assets/images/trophies/track.png
    - assets/images/loading.gif